# Generated by Django 5.0.6 on 2024-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='This book is making smart your thing', null=True),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='returned',
            field=models.DateField(default='<built-in method utcnow of type object at 0x59b5c8b788a0>'),
        ),
    ]
