# Generated by Django 5.0.6 on 2024-06-05 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.CharField(default='Give book after 7 days otherwise prepare to pay RS.10/day if issue date miss.', max_length=100),
        ),
        migrations.AddField(
            model_name='readbook',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readbook',
            name='issued_at',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 10, 27, 35, 172583)),
        ),
        migrations.AddField(
            model_name='readbook',
            name='returned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='This book is making smart your thing', null=True),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
