# Generated by Django 5.0.6 on 2024-06-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_description_alter_readbook_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.CharField(default='Give fine of RS.10/day if issue date miss.', max_length=100),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='returned',
            field=models.DateField(default='<built-in method utcnow of type object at 0x55d89a8038a0>'),
        ),
    ]
