# Generated by Django 5.0.6 on 2024-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_info_alter_readbook_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.CharField(default='Give book after 7 days otherwise prepare to pay RS.10/day if issue date miss.', max_length=100),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='returned',
            field=models.DateField(default='<built-in method utcnow of type object at 0x5fccf64588a0>'),
        ),
    ]
