# Generated by Django 5.0.6 on 2024-06-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_issued_readbook_librarian_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbook',
            name='librarian_issued_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='student_issued_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
