# Generated by Django 5.0.6 on 2024-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_readbook_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, max_length=5),
        ),
        migrations.AlterField(
            model_name='readbook',
            name='returned',
            field=models.DateField(default='<built-in method utcnow of type object at 0x594a51fbe8a0>'),
        ),
    ]
