# Generated by Django 5.0.6 on 2024-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_readbook_fine_alter_readbook_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbook',
            name='returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
