# Generated by Django 5.0.6 on 2024-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_readbook_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='returned_at',
            field=models.DateField(auto_now=True),
        ),
    ]
