# Generated by Django 5.0.6 on 2024-06-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_readbook_returned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readbook',
            name='returned_at',
        ),
    ]
